# Generated by Django 4.0.2 on 2022-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
